import fs from "fs/promises";
import path from "path";
import fsSync from "fs";
import type { Router } from "express";
import { scanExpressRouter } from "./scanExpressRouter";

/**
 * Modules klasöründeki index.ts dosyalarını import edip router içindeki endpoint’leri tarar,
 * OpenAPI 3.0 spec oluşturur.
 *
 * Kurallar:
 * - Base path: `${API_PREFIX}/${moduleName}`
 * - Varsayılan security: bearerAuth (JWT)
 * - Path içinde `/public` veya `/open` geçiyorsa security boş (public)
 * - Her endpoint’te zorunlu header: x-tenant (ör: gzl)
 */

function isExpressRouterInstance(x: any): x is Router {
  return !!x && typeof x === "function" && typeof x.use === "function" && typeof x.handle === "function";
}

function maybeCreateRouter(def: any): Router | undefined {
  // 1) Halihazırda Router instance mı?
  if (isExpressRouterInstance(def)) return def;

  // 2) Factory fonksiyon mu? (stack/handle yok → çağır)
  if (typeof def === "function" && !def.handle && !def.stack) {
    const r = def();
    if (isExpressRouterInstance(r)) return r;
  }

  // 3) Nesne olarak export edilmiş ama handle/use var
  if (def && typeof def.use === "function" && typeof def.handle === "function") {
    return def as Router;
  }

  return undefined;
}

export async function generateSwaggerFromRouters(writeToDisk = false) {
  const modulesRoot = path.resolve(__dirname, "..", "..", "modules");
  const apiPrefix = process.env.SWAGGER_API_PREFIX || "/api";
  const brand = process.env.BRAND_NAME || "MetaHub";
  const profile = process.env.APP_ENV || "dev";
  const apiVersion = process.env.API_VERSION || "1.0.0";
  const baseUrl = process.env.SWAGGER_BASE_URL || "http://localhost:5019";

  if (!fsSync.existsSync(modulesRoot)) {
    console.warn(`⚠️ Modules folder not found at: ${modulesRoot}`);
    return undefined;
  }

  // Modül klasörleri
  const dirents = await fs.readdir(modulesRoot, { withFileTypes: true });
  const modules = dirents
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort((a, b) => a.localeCompare(b));

  const tags: Array<{ name: string; description?: string }> = [];
  const paths: Record<string, any> = {};

  for (const moduleName of modules) {
    const importPathNoExt = path.join(modulesRoot, moduleName, "index.ts").replace(/\.ts$/, "");

    // Modül router’ını import et
    let modRouter: Router | undefined;
    try {
      const indexImport = await import(importPathNoExt);
      const def = indexImport?.default;

      modRouter = maybeCreateRouter(def);

      if (!modRouter) {
        console.warn(`⚠️ ${moduleName}: index.ts default export Router değil. Atlandı.`);
        continue;
      }
    } catch (err: any) {
      console.warn(`⚠️ ${moduleName}: index.ts import edilemedi. (${err?.message || err})`);
      continue;
    }

    // Modül iç rotalarını tara (mod bazında try/catch)
    let moduleRoutes = [];
    try {
      moduleRoutes = scanExpressRouter(modRouter);
    } catch (e: any) {
      console.warn(`⚠️ ${moduleName}: router scan sırasında hata: ${e?.message || e}`);
      continue;
    }

    if (moduleRoutes.length === 0) {
      console.warn(`⚠️ ${moduleName}: router içinde endpoint bulunamadı. Atlandı.`);
      continue;
    }

    // Tag ekle
    tags.push({ name: moduleName, description: `${moduleName} endpoints` });

    // Her route → OpenAPI path
    for (const r of moduleRoutes) {
      const fullPath = `${apiPrefix}/${moduleName}${r.path}`.replace(/\/{2,}/g, "/");
      const method = r.method.toLowerCase();

      if (!paths[fullPath]) paths[fullPath] = {};

      const isPublic = /\/(public|open)(\/|$)/i.test(fullPath);

      const pathSpec: any = {
        tags: [moduleName],
        summary: "",
        deprecated: false,
        security: isPublic ? [] : [{ bearerAuth: [] }],
        parameters: [
          {
            name: "x-tenant",
            in: "header",
            required: true,
            schema: { type: "string", example: "gzl" },
            description: "Tenant kimliği (zorunlu).",
          },
        ],
        responses: {
          200: { description: "Success" },
        },
      };

      paths[fullPath][method] = pathSpec;
    }
  }

  const spec = {
    openapi: "3.0.0",
    info: {
      title: `${brand} Backend API`,
      version: apiVersion,
      description: `📘 API documentation generated by router scanning (${profile}).`,
      contact: {
        name: `${brand} Support`,
        email: process.env.CONTACT_EMAIL || "support@example.com",
        url: process.env.CONTACT_URL || "https://example.com",
      },
      license: {
        name: "MIT",
        url: "https://opensource.org/licenses/MIT",
      },
    },
    servers: [
      {
        url: baseUrl,
        description: `Base URL for ${profile}`,
      },
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: "http",
          scheme: "bearer",
          bearerFormat: "JWT",
        },
      },
      parameters: {
        TenantHeader: {
          name: "x-tenant",
          in: "header",
          required: true,
          schema: { type: "string", example: "gzl" },
          description: "Tenant kimliği (zorunlu).",
        },
      },
    },
    security: [],
    tags,
    paths,
  };

  if (writeToDisk) {
    const outputPath = path.join(process.cwd(), "swagger.json");
    await fs.writeFile(outputPath, JSON.stringify(spec, null, 2));
    console.log(`📄 Swagger spec written to: ${outputPath}`);
  }

  console.log(`✅ Swagger generated by router scan. modules=${modules.length}, tags=${tags.length}`);
  return spec;
}
